### ISSUE TITLE
ResizeObserver depends on js allowInterop

### ISSUE THREAD

**Issue by kenzieschmoll** [dart-lang/html#102]
In order to use ResizeObserver, I had to use allowInterop from package:js/js.dart.
```
    final observer = html.ResizeObserver(allowInterop((entries, _) {
      _updateContainerForResize();
    }));
    observer.observe(element);
```
Seems like this isn't WAI, or if it is, maybe it could be documented in the API?

**Comment by natebosch** [comment]
Closing since I think we handled this on the SDK repo or somewhere else.
