### ISSUE TITLE
parsing of bad HTML goes into out-of-memory

### ISSUE THREAD

**Issue by isoos** [dart-lang/html#122]
- SDK: 2.9.0
- html: 0.14.0+3
- markup:
````
<html>
<body>
<button></p><p></button>
<button></p><p></button>
</body>
</html>
````

Calling `parse` on this results in out-of-memory on the Dart SDK.

**Comment by kevmoo** [comment]
CC @mit-mit 

Guessing this would be worth someone on the pub team looking at.

**Comment by isoos** [comment]
html5lib-python and Chrome parses the bad input above to the following output:
`<button><p></p><p></p></button><button><p></p><p></p></button></body>`
