### ISSUE TITLE
<a> Tag get Full link

### ISSUE THREAD

**Issue by shuike** [dart-lang/html#126]
`<a>` Tag get Full link
i use attributes["href"] cant get full link
i know Jsoup can use "abs:href" to get full link, but this labrary i can't use "abs:href" to get full link because this will be back null
what should i do to get full link like "http://xxxx.xxx/xxx/xxxx"
Thank's

**Comment by shuike** [comment]
```java
var document = getElementsByTagName("a").first.attributes["href"]); 
//will back `xxx/xx`, but i need to get full link like http://xxx.xxx/xxx/xx
//Jsoup can use "abs:href" to get full link

```

**Comment by bradcypert** [comment]
Hi @shuike! Any chance you can provide a code example that demonstrates the issue you're seeing? I'm specifically interested in the HTML that you're working with.

**Comment by akshdeep-singh** [comment]
Hi, any updates? I also need to get absolute url just like in Jsoup:
[https://jsoup.org/cookbook/extracting-data/working-with-urls](https://jsoup.org/cookbook/extracting-data/working-with-urls)
[https://jsoup.org/apidocs/org/jsoup/nodes/Node.html#absUrl(java.lang.String)](https://jsoup.org/apidocs/org/jsoup/nodes/Node.html#absUrl(java.lang.String))

**Comment by akshdeep-singh** [comment]
I found a solution though, if you have the url, you can use [Uri resolve(String reference)](https://api.dart.dev/stable/3.3.0/dart-core/Uri/resolve.html) method like this:
```dart
final uri = Uri.parse(url);
// get html for url
// final link = querySelector('a');
final absUri = uri.resolve(link.attributes['href']!);
```
