### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by evnor** [dart-lang/html#155]
The wiki page for [querySelector](https://pub.dev/documentation/html/latest/dom/Document/querySelector.html) has a spelling mistake. The last word, [UniplmentedError], should be [UnimplementedError]. See the screenshot. In the source documentation it is spelled correctly.
![image](https://user-images.githubusercontent.com/53000234/108641704-048f7800-74a1-11eb-9a43-863f49ddbfd3.png)

**Comment by devoncarew** [comment]
fixed in https://github.com/dart-lang/html/commit/137be8db5d5b7f00530fca1591292849ce6779c9
