### ISSUE TITLE
How do I get an element's html without its content ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [dart-lang/html#213]
I'd like to have only the html of the node itself, without its children. So `<div class="content"><p>text</p></div>` would give me `<div class="content"></div>`.

**Comment by fingerart** [comment]
You can do it like:

```dart
final el = doc.querySelector('div.content');
print(el?.clone(false).outerHtml);
```

**Comment by TheCarpetMerchant** [comment]
Ah, didn't know about this clone function. Thank you !
