### ISSUE TITLE
Question: Use this package or html5lib?

### ISSUE THREAD

**Issue by austincummings** [dart-lang/html#9]
Like the title says, should I use this package, or [html5lib](https://pub.dartlang.org/packages/html5lib)?

**Comment by sethladd** [comment]
If I understand correctly, this is the repo for html5lib.

@jmesserly to confirm ?

**Comment by jmesserly** [comment]
yup!

**Comment by sethladd** [comment]
Hopefully PR https://github.com/dart-lang/html/pull/10 makes it a bit more clear. Thanks for the question, @austincummings

**Comment by jmesserly** [comment]
actually reopening ... @sethladd  is it possible to update the description of the github repo? it still says "Dart port of html5lib 
https://pub.dartlang.org/packages/html5lib" ... the text is right but the link is wrong.

**Comment by sethladd** [comment]
I assume you want to change the link to https://pub.dartlang.org/packages/html ?

**Comment by jmesserly** [comment]
(it appears I don't have powers to do any admin stuff on this repo)

**Comment by jmesserly** [comment]
yup!

**Comment by sethladd** [comment]
Done and done!

**Comment by jmesserly** [comment]
thanks so much :)
